---

- name: Create directory for installation
  ansible.builtin.file:
    path: "{{ elastic_dir }}"
    state: directory

- name: Download the signing key
  tags: signkey
  become: true
  ansible.builtin.get_url:
    url: "{{ signkey_url }}"
    dest: "{{ elastic_dir }}"
  when: ansible_distribution == "Ubuntu"

- name: Extract gpg key
  tags: signkey
  become: true
  ansible.builtin.command:
    cmd: "gpg --dearmor --output /usr/share/keyrings/elasticsearch-keyring.gpg {{ elastic_dir }}/GPG-KEY-elasticsearch"
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  when: ansible_distribution == "Ubuntu"

- name: Import Signing Key for CentOS
  become: true
  ansible.builtin.rpm_key:
    key: "{{ signkey_url }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Download Elastic Search deb pkg
  ansible.builtin.get_url:
    url: "{{ debpkg_link }}"
    dest: "{{ elastic_dir }}"
    checksum: "sha512:{{ debpkg_chksum }}"
  when: ansible_distribution == "Ubuntu"

- name: Download Elastic Search rpm pkg
  ansible.builtin.get_url:
    url: " {{ rpmpkg_link }}"
    dest: "{{ elastic_dir }}"
    checksum: "sha512:{{ rpmpkg_chksum }}"
  when: ansible_distribution == "CentOS"

- name: Install from deb pkg
  tags: install
  become: true
  ansible.builtin.apt:
    deb: "{{ deb_elastic }}"
  when: ansible_distribution == "Ubuntu"

- name: Install from rpm pkg
  tags: install
  become: true
  ansible.builtin.dnf:
    name: "{{ rpm_elastic }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Configure the elasticsearch.yml for both hosts
  tags: config
  become: true
  ansible.builtin.blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    block: |
      cluster.name: my-cluster
      network.host: 0.0.0.0
      transport.host: 0.0.0.0
      action.auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*
    marker: "# {mark} ANSIBLE MANAGED ELASTICSEARCH CONFIG"

- name: Start the elasticsearch service
  tags: start
  become: true
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: true

- name: Reload systemd daemon
  tags: reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
